### ISSUE TITLE
container does not restart after haproxy process crashed

### ISSUE THREAD

**Issue by hpn0t0ad** [haproxytech/haproxy-docker-alpine-quic#2]
Hi! I'm running a container from the `haproxytech/haproxy-alpine-quic:2.8` image with compose with `restart: unless-stopped`.
Today, haproxy crashed for some reason:
```
FATAL: bug condition "!ncb_data(&qcs->rx.ncbuf, 0)" matched at src/mux_quic.c:2750
[ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
[NOTICE]   (1) : haproxy version is 2.8.0-fdd8154
[ALERT]    (1) : Current worker (128) exited with code 132 (Illegal instruction)
[WARNING]  (1) : Former worker (58) exited with code 143 (Terminated)
[WARNING]  (1) : Former worker (118) exited with code 143 (Terminated)
[WARNING]  (1) : Former worker (8) exited with code 143 (Terminated)
[WARNING]  (1) : Former worker (48) exited with code 143 (Terminated)
[WARNING]  (1) : All workers exited. Exiting... (132)
```
There is also this line in dmesg:
```
[Thu Jun 29 14:22:00 2023] traps: haproxy[64199] trap invalid opcode ip:55a47975c218 sp:7f609caaadc0 error:0 in haproxy[55a479708000+240000]
```

While this crash is probably not supposed to happen in the first place, it wouldn't actually be so bad if the container were to restart automatically and not stay around doing nothing. How can I ensure this works correctly?

**Comment by dkorunic** [comment]
To ensure Docker container automatically restarts in all cases, refer to the Docker [restart policy](https://docs.docker.com/config/containers/start-containers-automatically/) documentation and use **always** as a desired policy.
